config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/search', to: 'searches#search'

  resources :black_lists, only: %i(create destroy)

  resources :categories do
    resources :items, shallow: true do
      resources :suggestions, only: %i(create update destroy edit), shallow: true do
        put :apply, to: 'suggestions#apply'
      end
    end
  end
  resources :home, only: :index

  authenticated :user do
    root 'home#index'
  end
  root 'home#index'
end

app/views/layouts/shared/_footer.html.slim
footer.footer.pb-2.text-lighten
  .container-fluid
    .row
      hr.mb-3
      .col-sm-6
        p.text-center-xs &copy 2017 (c)
      .col-sm-6.hidden-xs

app/views/layouts/shared/_js_locales_info.html.slim
= javascript_tag do
  |  I18n.defaultLocale = "
  = I18n.default_locale
  | "; I18n.locale = "
  = I18n.locale
  | "; I18n.fallbacks = true; 

app/views/layouts/shared/_navigation.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      = link_to app_name, root_path, class: 'navbar-brand'
    ul.nav.navbar-nav
      li.dropdown#CategoryNavGroup
        a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          = t('activerecord.models.category.other')
          span.caret
        ul.dropdown-menu
          - if can? :create, Category
            li
              = nav_link(t('new'), new_category_path)
          li
            = nav_link(t('list'), categories_path)
    - if user_signed_in?
      ul.nav.navbar-nav.navbar-right
        li
          = link_to t('sign_out'), destroy_user_session_path, method: :delete
    - else
      ul.nav.navbar-nav.navbar-right
        li
          = nav_link(t('sign_up'), new_user_registration_path)
        li
          = nav_link(t('sign_in'), new_user_session_path)

app/views/layouts/shared/_title.html.slim
- provide(:title, title)
h1 = yield(:title)