config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/search', to: 'searches#search'

  resources :black_lists, only: %i(create destroy)

  resources :categories do
    resources :items, shallow: true do
      resources :suggestions, only: %i(create update destroy edit), shallow: true do
        put :apply, to: 'suggestions#apply'
      end
    end
  end
  resources :home, only: :index

  authenticated :user do
    root 'home#index'
  end
  root 'home#index'
end

app/models/item.rb
class Item < ApplicationRecord
  include Pictureable

  belongs_to :category
  belongs_to :user
  has_many :black_lists, dependent: :destroy
  has_many :suggestions, dependent: :destroy

  validates_presence_of :title, :description, :picture
  validates :title, uniqueness: { case_sensitive: false }

  scope :searchable, -> { where.not(id: BlackList.pluck(:item_id)) }
  scope :things_of_other, ->(user_id) { where.not(user_id: user_id) }
  scope :with_category, ->(category_id) { where(category_id: category_id) }

  def self.text_search(query)
    where(['title ilike :query',
           'description ilike :query'].join(' OR '), query: "%#{query}%")
  end

  def self.search(query)
    search_params = {
      category_id: :with_category,
      text: :text_search
    }

    result = where(nil)
    search_params.each do |k, v|
      result = result.send(v, query[k]) if query[k].present?
    end
    result
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :load_item, only: %i(update destroy show edit)
  before_action :load_category, only: %i(index new)

  authorize_resource

  def create
    @category = Category.find(params[:category_id])
    respond_with @item = @category.items.create(strong_params.merge(user_id: current_user.id))
  end

  def update
    @item.update(strong_params)
    respond_with @item
  end

  def destroy
    @category = Category.find(@item.category_id)
    respond_with(@category, @item.destroy)
  end

  def index
    @category = Category.find(params[:category_id])
    respond_with @items = @category.items
  end

  def show
    respond_with @item
  end

  def new
    respond_with @item = @category.items.new
  end

  def edit
    respond_with @item
  end

  private

  def load_category
    @category = Category.find(params[:category_id])
  end

  def load_item
    @item = Item.find(params[:id])
  end

  def strong_params
    params.require(:item).permit(:title, :description, :user_id, :picture)
  end
end

app/views/items/_form.html.slim
= form_for [@category, @item], html: { multipart: true } do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', required: true
  .form-group
    = f.label :description
    = f.text_field :description, class: 'form-control', required: true
  .form-group
    .pb-1
      - if @item.picture.exists?
        = image_tag image_path(@item.picture.url(:thumb))
    = f.label :picture
    = f.file_field :picture, class: 'form-control'
  .form-group
    = f.button t('save'), class: 'btn btn-primary btn-sm'

app/views/items/_item.html.slim
.panel.panel-default
  .panel-heading
    = link_to item.title, item_path(item.id)
  .panel-body
    = image_tag image_path(item.picture.url(:thumb))
    span.ml-2 = item.description
  .panel-footer
    - if can? :create, BlackList
      .js-filter-block
        - if !BlackList.permitted?(item_id: item.id, user_id: current_user.id) && !current_user.owner_of?(item)
          = link_to t('add_blacklist'), black_lists_path(item_id: item.id),
            method: :post, remote: true,
            class: 'btn btn-warning js-filter-on',
            id: "searchHide#{item.id}",
            data: {type: :json, item: item.id}
        - if BlackList.permitted?(item_id: item.id, user_id: current_user.id) && !current_user.owner_of?(item)
          = link_to t('remove_blacklist'), black_list_path(item.black_lists.first.id),
            method: :delete, remote: true,
            class: 'btn btn-success js-filter-off',
            id: "searchShow#{item.id}",
            data: {type: :json, item: item.id}

app/views/items/edit.html.slim
= render 'layouts/shared/title', title: t('.title')

.row
  .col-sm-6
    .panel.panel-default
      .panel-body
        = render 'items/form'

app/views/items/index.html.slim
= render 'layouts/shared/title', title: t('.title')
= render @items

app/views/items/new.html.slim
= render 'layouts/shared/title', title: t('.title')

.row
  .col-sm-6
    .panel.panel-default
      .panel-body
        = render 'items/form'

app/views/items/show.html.slim
= render 'layouts/shared/title', title: t('.title')
.panel.panel-default
  .panel-heading
    = @item.description
  .panel-body
    .row
      .col-xs-4.col-sm-3
        = image_tag image_path(@item.picture(:original)), class: 'img-responsive'
      .col-xs-8.col-sm-9
        .pt-2
          = @item.title
  - if can? :modify, @item
    .panel-footer
      ul.list-inline
        li
          = link_to t('edit'), edit_item_path(@item.id), class: 'btn btn-sm btn-warning'
        li
          = link_to t('delete'), item_path(@item.id), method: :delete, class: 'btn btn-sm btn-danger'

- if can? :create, Suggestion
  - unless Suggestion.permitted?(user_id: current_user.id, item_id: @item.id) || current_user.owner_of?(@item)
    hr
    = link_to t('add_suggestion'), item_suggestions_path(@item.id), method: :post, class: 'btn btn-lg btn-primary'
- if @item.suggestions.present?
  h3 #{t('.suggestion_title')}:
  - @item.suggestions.each do |i|
    .panel.panel-default.suggestion-card id="suggestion#{i.id}"
      .panel-heading
        = i.description
      .panel-body
        .row
          .col-xs-4.col-sm-3
            - if i.picture.present?
              = image_tag image_path(i.picture(:original)), class: 'img-responsive'
            - else
              = image_tag image_path(@item.picture(:original)), class: 'img-responsive'
          .col-xs-8.col-sm-9
            .pt-2
              = i.title

      .panel-footer
        ul.list-inline
          - if can? :apply, i
            li
              = link_to t('apply_suggestion'), suggestion_apply_path(i.id), method: :put, class: 'btn btn-sm btn-danger'
          - if can? :destroy, i
            li
              = link_to t('delete_suggestion'), suggestion_path(i.id), method: :delete, class: 'btn btn-sm btn-warning'