config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/search', to: 'searches#search'

  resources :black_lists, only: %i(create destroy)

  resources :categories do
    resources :items, shallow: true do
      resources :suggestions, only: %i(create update destroy edit), shallow: true do
        put :apply, to: 'suggestions#apply'
      end
    end
  end
  resources :home, only: :index

  authenticated :user do
    root 'home#index'
  end
  root 'home#index'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates_presence_of :title
  validates :title, uniqueness: { case_sensitive: false }

  def self.options_for_select
    all.map do |category|
      [category.title, category.id]
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: %i(update destroy show edit)

  authorize_resource

  def create
    respond_with @category = current_user.categories.create(strong_params)
  end

  def update
    @category.update(strong_params)
    respond_with @category
  end

  def destroy
    respond_with @category.destroy
  end

  def index
    respond_with @categories = Category.all
  end

  def show
    # @items = @category.items.page params[:page]
    @items = Kaminari.paginate_array(@category.items).page(params[:page]).per(10)
    respond_with @category
  end

  def new
    respond_with @category = Category.new
  end

  def edit
    respond_with @category
  end

  private

  def load_category
    @category = Category.find(params[:id])
  end

  def strong_params
    params.require(:category).permit(:title, :user_id)
  end
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  .form-group
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.button t('save'), class: 'btn btn-primary btn-sm'

app/views/categories/edit.html.slim
= render 'layouts/shared/title', title: t('.title')
.row
  .col-sm-6
    .panel.panel-default
      .panel-body
        = render 'categories/form'

app/views/categories/index.html.slim
= render 'layouts/shared/title', title: t('.title')
.list-group
  - @categories.each do |i|
    .list-group-item id="ListCategoryID_#{i.id}" = link_to i.title, category_path(i.id)

app/views/categories/new.html.slim
= render 'layouts/shared/title', title: t('.title')
.row
  .col-sm-6
    .panel.panel-default
      .panel-body
        = render 'categories/form'

app/views/categories/show.html.slim
= render 'layouts/shared/title', title: t('.title')
.panel.panel-default
  .panel-body
    p = @category.title
  - if can? :modify, @category
    .panel-footer
      ul.list-inline
        li
          = link_to t('edit'), edit_category_path(@category.id), class: 'btn btn-sm btn-warning'
        li
          = link_to t('delete'), category_path(@category.id), method: :delete, class: 'btn btn-sm btn-danger'

- if can? :modify, Item
  = link_to t('item.add'), new_category_item_path(@category.id), class: 'btn btn-lg btn-primary'
hr
- if @items.present?
  h3.text-capitalize = t('item', count: @category.items.count)
  /= render 'items/list', items: @category.items if @category.items.present?
  = render @items
  = paginate @items